Repository microsoft/terraform-provider-power-platform, pull requests merged in 2024-05, with the labels that each got.

#291 Fix proposition for the inversion between "Business" and "Non-business" connectors groups in Power Platform DLP policies
  internal/powerplatform/datasource_dlp_policy_test.go
  internal/powerplatform/resource_dlp_policy_test.go
  internal/powerplatform/services/dlp_policy/datasource_dlp_policy.go
  internal/powerplatform/services/dlp_policy/resource_dlp_policy.go
Labels: bug

#290 Updating developer guide with additional Information
  DEVELOPER.md
Labels: documentation

#292 resource/datasource primary id should not changes on reapply
  docs/data-sources/billing_policies.md
  docs/data-sources/data_loss_prevention_policies.md
  docs/data-sources/environment_powerapps.md
  docs/data-sources/environment_settings.md
  docs/data-sources/environments.md
  docs/data-sources/solutions.md
  docs/data-sources/tenant_settings.md
  docs/resources/environment_settings.md
  docs/resources/tenant_settings.md
  go.mod
  internal/powerplatform/datasource_applications_test.go
  internal/powerplatform/datasource_environment_application_packages_test.go
  internal/powerplatform/datasource_environment_settings_test.go
  internal/powerplatform/datasource_securityroles_test.go
  internal/powerplatform/datasource_solutions_test.go
  internal/powerplatform/datasource_tenant_settings_test.go
  internal/powerplatform/mocks/mock_helpers.go
  internal/powerplatform/resource_billing_policy_test.go
  internal/powerplatform/resource_dlp_policy_test.go
  internal/powerplatform/resource_environment_application_package_install_test.go
  internal/powerplatform/resource_environment_settings_test.go
  internal/powerplatform/resource_environment_test.go
  internal/powerplatform/resource_managed_environment_test.go
  internal/powerplatform/resource_solution_test.go
  internal/powerplatform/resource_user_test.go
  internal/powerplatform/services/application/datasource_environment_application_packages.go
  internal/powerplatform/services/application/datasource_tenant_application_packages.go
  internal/powerplatform/services/application/resource_environment_application_package_install.go
  internal/powerplatform/services/authorization/datasource_securityroles.go
  internal/powerplatform/services/connectors/datasource_connectors.go
  internal/powerplatform/services/currencies/datasource_currencies.go
  internal/powerplatform/services/dlp_policy/datasource_dlp_policy.go
  internal/powerplatform/services/environment/datasource_environments.go
  internal/powerplatform/services/environment_settings/datasource_environment_settings.go
  internal/powerplatform/services/environment_settings/models_environment_settings.go
  internal/powerplatform/services/environment_settings/resources_environment_settings.go
  internal/powerplatform/services/environment_templates/datasource_environment_templates.go
  internal/powerplatform/services/languages/datasource_languages.go
  internal/powerplatform/services/licensing/datasource_billing_policies.go
  internal/powerplatform/services/locations/datasource_locations.go
  internal/powerplatform/services/powerapps/datasource_environment_powerapps.go
  internal/powerplatform/services/solution/datasource_solutions.go
  internal/powerplatform/services/solution/resource_solution.go
  internal/powerplatform/services/tenant_settings/api_tenant_settings.go
  internal/powerplatform/services/tenant_settings/datasource_tenant_settings.go
  internal/powerplatform/services/tenant_settings/models_tenant_settings.go
  internal/powerplatform/services/tenant_settings/resource_tenant_settings.go
Labels: enhancement, resource, data source

#315 Fix broken documentation links
  .devcontainer/features/pac/devcontainer-feature.json
  docs/data-sources/billing_policies.md
  docs/data-sources/billing_policies_environments.md
  docs/data-sources/connectors.md
  docs/data-sources/currencies.md
  docs/data-sources/data_loss_prevention_policies.md
  docs/data-sources/environment_application_packages.md
  docs/data-sources/environment_powerapps.md
  docs/data-sources/environment_settings.md
  docs/data-sources/environments.md
  docs/data-sources/languages.md
  docs/data-sources/locations.md
  docs/data-sources/security_roles.md
  docs/data-sources/solutions.md
  docs/data-sources/tenant_settings.md
  docs/guides/app_registration.md
  docs/guides/nonpublic_clouds.md
  docs/index.md
  docs/resources/billing_policy.md
  docs/resources/billing_policy_environment.md
  docs/resources/data_loss_prevention_policy.md
  docs/resources/environment.md
  docs/resources/environment_application_package_install.md
  docs/resources/environment_settings.md
  docs/resources/managed_environment.md
  docs/resources/solution.md
  docs/resources/tenant_settings.md
  docs/resources/user.md
  internal/powerplatform/services/application/datasource_environment_application_packages.go
  internal/powerplatform/services/application/resource_environment_application_package_install.go
  internal/powerplatform/services/application/tests/datasource/tenant_application_packages/Validate_Read/get_tenant_applications.json
  internal/powerplatform/services/application/tests/datasource/tenant_application_packages/Validate_Read_Filter/get_tenant_applications.json
  internal/powerplatform/services/authorization/datasource_securityroles.go
  internal/powerplatform/services/authorization/resource_user.go
  internal/powerplatform/services/connectors/datasource_connectors.go
  internal/powerplatform/services/currencies/datasource_currencies.go
  internal/powerplatform/services/dlp_policy/datasource_dlp_policy.go
  internal/powerplatform/services/dlp_policy/resource_dlp_policy.go
  internal/powerplatform/services/environment/datasource_environments.go
  internal/powerplatform/services/environment/resource_environment.go
  internal/powerplatform/services/environment_settings/datasource_environment_settings.go
  internal/powerplatform/services/environment_settings/resources_environment_settings.go
  internal/powerplatform/services/languages/datasource_languages.go
  internal/powerplatform/services/licensing/datasource_billing_policies.go
  internal/powerplatform/services/licensing/datasource_billing_policies_environments.go
  internal/powerplatform/services/licensing/resource_billing_policy.go
  internal/powerplatform/services/licensing/resource_billing_policy_environment.go
  internal/powerplatform/services/locations/datasource_locations.go
  internal/powerplatform/services/managed_environment/resource_managed_environment.go
  internal/powerplatform/services/powerapps/datasource_environment_powerapps.go
  internal/powerplatform/services/solution/datasource_solutions.go
  internal/powerplatform/services/solution/resource_solution.go
  internal/powerplatform/services/tenant_settings/datasource_tenant_settings.go
  internal/powerplatform/services/tenant_settings/resource_tenant_settings.go
  templates/guides/app_registration.md.tmpl
  templates/guides/nonpublic_clouds.md.tmpl
  templates/index.md.tmpl
  templates/resources/environment.md.tmpl
Labels: documentation

#316 resource deletions outside terraform state should not end with an error when using terraform refresh
  .devcontainer/features/local_provider_dev/terraform.rc
  internal/powerplatform/helpers/error.go
  internal/powerplatform/services/authorization/api_user.go
  internal/powerplatform/services/authorization/resource_user.go
  internal/powerplatform/services/dlp_policy/api_dlp_policy.go
  internal/powerplatform/services/dlp_policy/resource_dlp_policy.go
  internal/powerplatform/services/environment/api_environment.go
  internal/powerplatform/services/environment/resource_environment.go
  internal/powerplatform/services/licensing/api_licensing.go
  internal/powerplatform/services/licensing/resource_billing_policy.go
  internal/powerplatform/services/licensing/resource_billing_policy_environment.go
  internal/powerplatform/services/licensing/test/resource/environments/Validate_Update/get_environments_for_policy_8.json
  internal/powerplatform/services/licensing/test/resource/environments/Validate_Update/get_environments_for_policy_9.json
  internal/powerplatform/services/managed_environment/resource_managed_environment.go
  internal/powerplatform/services/solution/api_solution.go
  internal/powerplatform/services/solution/resource_solution.go
Labels: bug, enhancement, resource
