Repository microsoft/terraform-provider-power-platform, pull requests merged in 2025-05, with the labels that each got.

#723 Fix #705: Replace panic with error handling in environment_settings
  .changes/unreleased/fixed-20250424-161548.yaml
  internal/services/environment_settings/datasource_environment_settings.go
  internal/services/environment_settings/models.go
  internal/services/environment_settings/resources_environment_settings.go
Labels: go, ai assisted

#755 Adding additional CodeQL scanning
  .devcontainer/devcontainer.json
  .devcontainer/features/local_provider_dev/install.sh
  .github/codeql/terraform-providers-go/codeql-pack.lock.yml
  .github/codeql/terraform-providers-go/codeql-pack.yml
  .github/codeql/terraform-providers-go/no_panic.ql
  .github/prompts/codeql.prompt.md
  .github/prompts/codeql2.prompt.md
  .github/workflows/codeql.yml
  .gitignore
  .vscode/settings.json
Labels: github_actions, developer experience, skip-changelog

#763 feat: add postCreate script for GitHub CLI extension installation
  .devcontainer/devcontainer.json
  .devcontainer/features/local_provider_dev/install.sh
  .devcontainer/postCreate.sh
Labels: skip-changelog

#764 Create codeql2.yml
  .github/workflows/codeql2.yml
Labels: skip-changelog

#744 fix(errors): improve error handling by wrapping errors with context
  .changes/unreleased/fixed-20250428-083438.yaml
  internal/api/auth.go
  internal/services/admin_management_application/resource_admin_management_application.go
  internal/services/capacity/datasource_tenant_capacity.go
  internal/services/connectors/datasource_connectors.go
  internal/services/dlp_policy/helpers.go
  internal/services/environment_group_rule_set/dto.go
  internal/services/environment_settings/models.go
  internal/services/managed_environment/api_managed_environment.go
  internal/services/solution/resource_solution_test.go
  internal/services/tenant/datasource_tenant.go
  internal/services/tenant_isolation_policy/api_tenant_isolation_policy.go
  internal/services/tenant_settings/dto.go
Labels: enhancement, ai assisted

#768 Governance framework for the Terraform Provider
  .changes/unreleased/documentation-20250513-045753.yaml
  GOVERNANCE.md
Labels: documentation

#769 Merge changelog entries for v3.7.1 release
  .changes/3.7.1.md
  .changes/unreleased/documentation-20250513-045753.yaml
  .changes/unreleased/fixed-20250424-150958.yaml
  .changes/unreleased/fixed-20250424-161548.yaml
  .changes/unreleased/fixed-20250425-075151.yaml
  .changes/unreleased/fixed-20250425-110134.yaml
  .changes/unreleased/fixed-20250428-083438.yaml
  .changes/unreleased/fixed-20250428-231444.yaml
  .changes/unreleased/fixed-20250429-153504.yaml
  .changes/unreleased/fixed-20250430-064642.yaml
  .changes/unreleased/fixed-20250505-112544.yaml
  .changes/unreleased/fixed-20250512-095307.yaml
  CHANGELOG.md
Labels: skip-changelog

#776 3.7.2 release
  .changes/3.7.2.md
  .changes/unreleased/fixed-20250516-095207.yaml
  CHANGELOG.md
Labels: release, skip-changelog

#784 Update release_prep workflow
  .github/workflows/release_prep.yml
Labels: skip-changelog, codex
