Repository microsoft/terraform-provider-power-platform, pull requests merged in 2025-03, with the labels that each got.

#597 Bug: 596-bug-unit-and-acceptance-test-verification-for-managed-environments
  internal/services/environment/resource_environment.go
  internal/services/environment/resource_environment_test.go
  internal/services/managed_environment/resource_managed_environment_test.go
Labels: skip-changelog

#619 release docs for v3.4.0
  .changes/3.4.0.md
  .changes/unreleased/added-20241218.yaml
  .changes/unreleased/added-20250108-124040.yaml
  .changes/unreleased/added-20250120-091335.yaml
  .changes/unreleased/added-20250130-001524.yaml
  .changes/unreleased/added-20250130-130228.yaml
  .changes/unreleased/added-20250205-135809.yaml
  .changes/unreleased/added-20250214-153010.yaml
  .changes/unreleased/added-20250220-141238.yaml
  .changes/unreleased/changed-20250227-161415.yaml
  .changes/unreleased/documentation-20241204-093950.yaml
  .changes/unreleased/documentation-20250220-032105.yaml
  .changes/unreleased/fixed-20250116-113458.yaml
  .changes/unreleased/fixed-20250124-153618.yaml
  .changes/unreleased/fixed-20250224-105933.yaml
  CHANGELOG.md
Labels: skip-changelog

#621 Lifecycle operation will retry if 'Failed' status was return.
  .changes/unreleased/fixed-20250306-142223.yaml
  internal/api/lifecycle.go
  internal/services/enterprise_policy/api_enterprise_policy.go
  internal/services/environment/api_environment.go
  internal/services/environment/resource_environment_test.go
  internal/services/environment/tests/resource/Validate_Retry_LidecycleOperation/get_environment_00000000-0000-0000-0000-000000000001.json
  internal/services/environment/tests/resource/Validate_Retry_LidecycleOperation/get_lifecycle.json
  internal/services/environment/tests/resource/Validate_Retry_LidecycleOperation/get_lifecycle_delete_1.json
  internal/services/environment/tests/resource/Validate_Retry_LidecycleOperation/get_lifecycle_delete_2.json
  internal/services/environment/tests/resource/Validate_Retry_LidecycleOperation/get_lifecycle_delete_3.json
  internal/services/licensing/api_licensing.go
  internal/services/managed_environment/api_managed_environment.go
  internal/services/solution/api_solution.go
Labels: bug, enhancement, resource

#609 Docs: Add guidelines for contributors
  .changes/unreleased/documentation-20250303-071315.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/data_source.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/resource.md
  .github/prompts/resource.prompt.md
  CONTRIBUTING.md
  DEVELOPER.md
  README.md
  decision-log/loosely_typed_resources.md
  devdocs/adr/httpmocks.md
  devdocs/adr/loosely_typed_data_records.md
  devdocs/community_support.md
  devdocs/feature_request_guidelines.md
  devdocs/observability_guidelines.md
  devdocs/playbook/resource.md
  devdocs/release_guidelines.md
  devdocs/schema_guidelines.md
  devdocs/security_guidelines.md
  devdocs/testing_guidelines.md
  docs/guides/dynamic_configuration.md
  templates/guides/dynamic_configuration.md.tmpl
Labels: documentation, developer experience

#629 Add GitHub Actions workflow for weekly repository metrics collection
  .github/workflows/metrics.yml
Labels: skip-changelog, ai assisted

#631 Add installation script for the latest GitHub CLI version
  .devcontainer/features/local_provider_dev/install.sh
Labels: skip-changelog, ai assisted

#640 Removing TestAccEnvironmentsResource_Create_Environment_No_Dataverse_Add_Dataverse_With_Env_Group
  internal/services/environment/resource_environment_test.go
Labels: bug, skip-changelog

#627 Enhance release workflow: add release preparation job and update rele…
  .github/workflows/release.yml
  .github/workflows/release_prep.yml
  .gitignore
Labels: skip-changelog, ai assisted

#610 auxiliary tenant IDs in the authentication process
  .changes/unreleased/added-20250303-045037.yaml
  internal/api/auth.go
  internal/config/config.go
  internal/constants/constants.go
  internal/helpers/config.go
  internal/provider/provider.go
  internal/services/environment/resource_environment_test.go
Labels: enhancement

#642 Tool network tracing for debugging
  .devcontainer/features/local_provider_dev/install.sh
  DEVELOPER.md
  devdocs/adr/mitmproxy.md
  devdocs/testing_guidelines.md
  makefile
Labels: developer experience, skip-changelog, ai assisted

#646 Update GitHub workflows to use GITHUB_OUTPUT
  .github/workflows/run_tests.yml
Labels: run-acceptance-tests, skip-changelog, ai assisted

#618 `powerplatform_tenant_isolation_policy` resource
  .changes/unreleased/added-20250306-042937.yaml
  .devcontainer/devcontainer.json
  .github/copilot-instructions.md
  .github/prompts/testing.prompt.md
  .gitignore
  .golangci.yml
  .vscode/launch.json
  docs/resources/tenant_isolation_policy.md
  examples/resources/powerplatform_tenant_isolation_policy/resource.tf
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/services/tenant_isolation_policy/api_tenant_isolation_policy.go
  internal/services/tenant_isolation_policy/dto.go
  internal/services/tenant_isolation_policy/models.go
  internal/services/tenant_isolation_policy/resource_tenant_isolation_policy.go
  internal/services/tenant_isolation_policy/resource_tenant_isolation_policy_test.go
  internal/services/tenant_isolation_policy/tests/resource/Validate_Create/policy_response.json
  internal/services/tenant_isolation_policy/tests/resource/Validate_Create/response.json
  internal/services/tenant_isolation_policy/tests/resource/Validate_Create_Error/error_response.json
  internal/services/tenant_isolation_policy/tests/resource/Validate_Delete/empty_policy.json
  internal/services/tenant_isolation_policy/tests/resource/Validate_Delete/initial_policy.json
  internal/services/tenant_isolation_policy/tests/resource/Validate_Delete/policy.json
  internal/services/tenant_isolation_policy/tests/resource/Validate_Update/initial_policy.json
  internal/services/tenant_isolation_policy/tests/resource/Validate_Update/initial_state.json
  internal/services/tenant_isolation_policy/tests/resource/Validate_Update/updated_policy.json
  internal/services/tenant_isolation_policy/tests/resource/Validate_Update/updated_state.json
  internal/services/tenant_isolation_policy/tests/resource/empty_policy.json
  internal/services/tenant_isolation_policy/tests/resource/get_empty_policy.json
  internal/services/tenant_isolation_policy/tests/resource/get_tenant.json
  internal/services/tenant_isolation_policy/tests/resource/tenant.json
  makefile
Labels: ai assisted

#644 Add junit report generation and upload to Codecov
  .github/workflows/run_tests.yml
  .gitignore
Labels: github_actions, tool, run-acceptance-tests, skip-changelog

#654 Refactor error handling to use errors.New to fix linter errors
  internal/api/auth.go
  internal/helpers/array/array.go
  internal/services/authorization/api_user.go
  internal/services/copilot_studio_application_insights/api_copilot_studio_application_insights.go
  internal/services/data_record/api_data_record.go
  internal/services/data_record/resource_data_record.go
  internal/services/data_record/resource_data_record_test.go
  internal/services/environment/models.go
  internal/services/environment/resource_environment.go
  internal/services/environment_group_rule_set/dto.go
  internal/services/environment_settings/models.go
  internal/services/managed_environment/api_managed_environment.go
  internal/services/solution/api_solution.go
  internal/services/tenant_isolation_policy/api_tenant_isolation_policy.go
  internal/services/tenant_settings/dto.go
  makefile
  scripts/user_story_prompt.sh
Labels: bug, skip-changelog, ai assisted

#635 `powerplatform_analytics_data_exports` data source
  .changes/unreleased/added-20250308-084936.yaml
  .devcontainer/devcontainer.json
  .devcontainer/features/local_provider_dev/install.sh
  .github/copilot-instructions.md
  .github/prompts/testing.prompt.md
  docs/data-sources/analytics_data_exports.md
  examples/data-sources/powerplatform_analytics_data_exports/data-source.tf
  examples/data-sources/powerplatform_analytics_data_exports/outputs.tf
  internal/api/client.go
  internal/config/config.go
  internal/constants/constants.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/services/analytics_data_export/api_analytics_data_exports.go
  internal/services/analytics_data_export/datasource_analytics_data_exports.go
  internal/services/analytics_data_export/datasource_analytics_data_exports_test.go
  internal/services/analytics_data_export/dto.go
  internal/services/analytics_data_export/models.go
  internal/services/analytics_data_export/tests/datasource/Validate_Read/get_analytics_data_exports.json
  internal/services/analytics_data_export/tests/datasource/Validate_Read/get_gateway_cluster.json
  internal/services/analytics_data_export/tests/datasource/Validate_Read/get_tenant.json
  internal/services/data_record/resource_data_record.go
  internal/services/environment/resource_environment_test.go
Labels: data source, ai assisted

#650 Only markdowndescription should be use to define attributes documentation
  .changes/unreleased/changed-20250319-082014.yaml
  docs/data-sources/connection_shares.md
  internal/provider/provider.go
  internal/services/admin_management_application/resource_admin_management_application.go
  internal/services/application/datasource_environment_application_packages.go
  internal/services/application/datasource_tenant_application_packages.go
  internal/services/application/resource_environment_application_package_install.go
  internal/services/authorization/datasource_securityroles.go
  internal/services/authorization/resource_user.go
  internal/services/capacity/datasource_tenant_capacity.go
  internal/services/connection/datasource_connection_shares.go
  internal/services/connection/datasource_connections.go
  internal/services/connectors/datasource_connectors.go
  internal/services/currencies/datasource_currencies.go
  internal/services/data_record/resource_data_record.go
  internal/services/dlp_policy/datasource_dlp_policy.go
  internal/services/environment/datasource_environments.go
  internal/services/environment/resource_environment.go
  internal/services/environment_settings/datasource_environment_settings.go
  internal/services/environment_templates/datasource_environment_templates.go
  internal/services/languages/datasource_languages.go
  internal/services/licensing/datasource_billing_policies.go
  internal/services/licensing/datasource_billing_policies_environments.go
  internal/services/licensing/resource_billing_policy.go
  internal/services/licensing/resource_billing_policy_environment.go
  internal/services/locations/datasource_locations.go
  internal/services/managed_environment/resource_managed_environment.go
  internal/services/powerapps/datasource_environment_powerapps.go
  internal/services/rest/resource_rest.go
  internal/services/solution/datasource_solutions.go
  internal/services/solution/resource_solution.go
  internal/services/solution_checker_rules/datasource_solution_checker_rules.go
  internal/services/tenant/datasource_tenant.go
  internal/services/tenant_settings/datasource_tenant_settings.go
  internal/services/tenant_settings/resource_tenant_settings.go
Labels: documentation, ai assisted

#656 Fixing changie formatting error
  .changes/unreleased/added-20250306-224522.yaml
  .changes/unreleased/fixed-20250305-121234.yaml
  .changes/unreleased/fixed-20250306-154637.yaml
Labels: skip-changelog

#658 update release prep pipeline to use deploy keys
  .github/workflows/release_prep.yml
Labels: release, skip-changelog

#652 Feat: add powerplatform_environment_wave resource and related functionality
  .changes/unreleased/added-20250319-151718.yaml
  .github/copilot-instructions.md
  DEVELOPER.md
  docs/resources/environment_wave.md
  examples/resources/powerplatform_environment_wave/resource.tf
  internal/api/client.go
  internal/config/config.go
  internal/constants/constants.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/services/environment/resource_environment.go
  internal/services/environment_wave/api_environment_wave.go
  internal/services/environment_wave/models.go
  internal/services/environment_wave/resource_environment_wave.go
  internal/services/environment_wave/resource_environment_wave_test.go
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_Create/get_environment_00000000-0000-0000-0000-000000000001.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_Create/get_features_enabled.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_Create/get_features_upgrading.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_Create/get_organizations.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_Error/get_environment_00000000-0000-0000-0000-000000000001.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_Error/get_features_failed.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_Error/get_organizations.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_FailedDuringUpgrade/get_environment_00000000-0000-0000-0000-000000000001.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_FailedDuringUpgrade/get_features_failed.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_FailedDuringUpgrade/get_features_upgrading.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_FailedDuringUpgrade/get_organizations.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_NotFound/get_environment_00000000-0000-0000-0000-000000000001.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_NotFound/get_organizations.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_UnsupportedState/get_environment_00000000-0000-0000-0000-000000000001.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_UnsupportedState/get_features_unknown.json
  internal/services/environment_wave/test/resource/EnvironmentWaveResource_UnsupportedState/get_organizations.json
Labels: resource, ai assisted

#664 improve copilot instructions
  .github/copilot-instructions.md
  .vscode/settings.json
  docs/resources/environment_application_package_install.md
  internal/services/application/resource_environment_application_package_install.go
  makefile
Labels: developer experience, skip-changelog, ai assisted
