Repository microsoft/terraform-provider-power-platform, pull requests merged in 2025-04, with the labels that each got.

#679 added documentation how to turn off Azure CLI telemetry
  .changes/unreleased/documentation-20250401-093438.yaml
  .devcontainer/features/local_provider_dev/install.sh
  docs/index.md
  templates/index.md.tmpl
Labels: documentation

#681 Docs: Update public preview resources in README and documentation
  README.md
  docs/data-sources/analytics_data_exports.md
  docs/index.md
  docs/resources/copilot_studio_application_insights.md
  docs/resources/environment.md
  docs/resources/environment_group_rule_set.md
  docs/resources/environment_wave.md
  internal/services/analytics_data_export/datasource_analytics_data_exports.go
  internal/services/copilot_studio_application_insights/resource_copilot_studio_application_insights.go
  internal/services/environment/resource_environment.go
  internal/services/environment_group_rule_set/resource_environment_group_rule_set.go
  internal/services/environment_wave/resource_environment_wave.go
  templates/index.md.tmpl
  templates/resources/environment.md.tmpl
Labels: skip-changelog

#697 Chore: Update permissions in changelog workflow
  .github/workflows/check_changie_comment_on_pr.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/metrics.yml
  .github/workflows/release.yml
  .github/workflows/release_prep.yml
  .github/workflows/run_tests.yml
  .github/workflows/terraform_provider.yml
Labels: security, skip-changelog, ai assisted

#695 Adding documentation and samples for Azure DevOps authentication with Workload Identity Federation
  .changes/unreleased/documentation-20250409-224908.yaml
  docs/index.md
  templates/index.md.tmpl
Labels: bug, documentation

#713 Fix: Update error message in Delete function and correct debug log fo…
  .changes/unreleased/fixed-20250414-165632.yaml
  internal/services/authorization/resource_user.go
Labels: ai assisted

#669 Implement Continuous Access Evaluation (CAE) support
  .changes/unreleased/added-20250328-083958.yaml
  docs/guides/continuous_access_evaluation.md
  examples/provider/provider_with_cae.tf
  internal/api/auth.go
  internal/api/auth_test.go
  internal/api/client.go
  internal/api/client_test.go
  internal/api/request.go
  internal/config/config.go
  internal/constants/constants.go
  internal/provider/provider.go
  templates/guides/continuous_access_evaluation.md.tmpl
Labels: security, ai assisted

#712 Update CODEOWNERS
  CODEOWNERS
Labels: github_actions, skip-changelog

#725 Update CODEOWNERS
  CODEOWNERS
Labels: skip-changelog

#726 changelog
  .changes/3.6.0.md
  .changes/unreleased/added-20250313-153044.yaml
  .changes/unreleased/added-20250319-151718.yaml
  .changes/unreleased/added-20250328-083958.yaml
  .changes/unreleased/documentation-20250401-093438.yaml
  .changes/unreleased/documentation-20250409-224908.yaml
  .changes/unreleased/fixed-20250328-112001.yaml
  .changes/unreleased/fixed-20250331-124817.yaml
  .changes/unreleased/fixed-20250407-075519.yaml
  .changes/unreleased/fixed-20250409-073556.yaml
  .changes/unreleased/fixed-20250411-043430.yaml
  .changes/unreleased/fixed-20250414-165632.yaml
  .changes/unreleased/fixed-20250415-185454.yaml
  CHANGELOG.md
Labels: skip-changelog

#720 Corrected validator logic in OtherFieldRequiredWhenValueOfValidator to properly handle field comparison cases
  .changes/unreleased/fixed-20250424-143838.yaml
  internal/validators/other_field_required_when_value_of_validator.go
Labels: go, ai assisted

#722 Fix #703: Update StringSliceToSet to return error instead of panicking
  .changes/unreleased/fixed-20250424-152806.yaml
  internal/helpers/string_to_set.go
  internal/helpers/string_to_set_test.go
  internal/services/managed_environment/resource_managed_environment.go
Labels: enhancement, go, ai assisted

#746 fix: add http.StatusConflict to API response handling lifecycle operations
  .changes/unreleased/fixed-20250428-093846.yaml
  internal/services/enterprise_policy/api_enterprise_policy.go
  internal/services/environment/api_environment.go
  internal/services/managed_environment/api_managed_environment.go
Labels: bug, resource

#743 fix: correct typos in error messages and debug logs in User resource
  .changes/unreleased/fixed-20250428-083052.yaml
  internal/services/authorization/resource_user.go
Labels: enhancement, ai assisted

#724 fix: improve error handling in tenant settings conversion functions
  .changes/unreleased/fixed-20250424-182510.yaml
  internal/services/tenant_settings/datasource_tenant_settings.go
  internal/services/tenant_settings/dto.go
  internal/services/tenant_settings/resource_tenant_settings.go
Labels: enhancement, go, ai assisted

#750 chore: update changelog and release notes for version 3.7.0
  .changes/3.7.0.md
  .changes/unreleased/added-20250424-132557.yaml
  .changes/unreleased/changed-20250428-210552.yaml
  .changes/unreleased/documentation-20250426-224430.yaml
  .changes/unreleased/fixed-20250424-143838.yaml
  .changes/unreleased/fixed-20250424-152806.yaml
  .changes/unreleased/fixed-20250424-182510.yaml
  .changes/unreleased/fixed-20250428-083052.yaml
  .changes/unreleased/fixed-20250428-093846.yaml
  CHANGELOG.md
Labels: skip-changelog

#748 Fix validation logic for required fields in configuration
  .changes/unreleased/fixed-20250428-231444.yaml
  internal/validators/make_field_required_when_other_field_does_not_have_value_validator.go
Labels: ai assisted

#752 Fix #704: Replace panic with proper error handling in ExecuteApiRequest function
  .changes/unreleased/fixed-20250430-064642.yaml
  internal/services/rest/api_rest.go
Labels: enhancement, ai assisted

#751 fix: improve DeleteEnvironment function to handle 404 responses gracefully
  .changes/unreleased/fixed-20250425-110134.yaml
  internal/services/environment/api_environment.go
Labels: enhancement, ai assisted
