Repository microsoft/terraform-provider-power-platform, pull requests merged in 2025-02, with the labels that each got.

#545 Add Auth Options: User-Managed Identity, System-Managed Identity, and AzDO Workload Identity Federation
  .changes/unreleased/added-20241218.yaml
  docs/index.md
  internal/api/auth.go
  internal/api/client_test.go
  internal/config/config.go
  internal/constants/constants.go
  internal/provider/provider.go
  templates/index.md.tmpl
Labels: enhancement, security

#568 enhance powerplatform_environment to allow on behalf of developer environments
  .changes/unreleased/added-20250130-130228.yaml
  docs/data-sources/environments.md
  docs/resources/environment.md
  internal/services/copilot_studio_application_insights/resource_copilot_studio_application_insights_test.go
  internal/services/copilot_studio_application_insights/tests/Test_Files/exampleagent_1_0_0_1_managed.zip
  internal/services/copilot_studio_application_insights/tests/Test_Files/testagent_1_0_0_1_managed.zip
  internal/services/environment/api_environment.go
  internal/services/environment/datasource_environments.go
  internal/services/environment/datasource_environments_test.go
  internal/services/environment/dto.go
  internal/services/environment/models.go
  internal/services/environment/resource_environment.go
  internal/services/environment/resource_environment_test.go
  internal/services/environment/tests/resource/Validate_Create_Dev_Env/get_environment_00000000-0000-0000-0000-000000000001.json
  internal/services/environment/tests/resource/Validate_Create_Dev_Env/get_lifecycle.json
  internal/services/environment/tests/resource/Validate_Create_Dev_Env/get_lifecycle_delete.json
  internal/validators/make_field_required_when_other_field_does_not_have_value.go
  internal/validators/make_field_required_when_other_field_does_not_have_value_validator.go
  internal/validators/other_field_required_when_value_of.go
  internal/validators/other_field_required_when_value_of_validator.go
Labels: enhancement

#587 Document the design decision for loosely typed resources
  CONTRIBUTING.md
  decision-log/loosely_typed_resources.md
Labels: documentation, skip-changelog

#581 powerplatform_environment: support service principal when creating dev environments "on behalf of"
  docs/resources/environment.md
  internal/services/environment/dto.go
  internal/services/environment/models.go
  internal/services/environment/resource_environment.go
Labels: bug, skip-changelog

#599 Bug: environment copilot acceptance test verification
  docs/resources/copilot_studio_application_insights.md
  internal/services/copilot_studio_application_insights/api_copilot_studio_application_insights.go
  internal/services/copilot_studio_application_insights/resource_copilot_studio_application_insights.go
  internal/services/copilot_studio_application_insights/resource_copilot_studio_application_insights_test.go
  internal/services/environment/resource_environment_test.go
Labels: bug, skip-changelog

#595 powerplatform_environment: fixing bug that updating display_name field triggers manager environment to enable itself
  .changes/unreleased/fixed-20250224-105933.yaml
  docs/resources/environment.md
  examples/resources/powerplatform_environment/resource.tf
  internal/services/environment/api_environment.go
  internal/services/environment/dto.go
  internal/services/environment/models.go
  internal/services/environment/resource_environment.go
  internal/services/environment/resource_environment_test.go
  internal/services/environment/tests/resource/Validate_Create_And_Update/get_environment_2.json
  internal/services/managed_environment/api_managed_environment.go
Labels: bug
